
services:
  dvwa-serivce:
    image: vulnerables/web-dvwa
    container_name: vulnerable-container
    restart: unless-stopped
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - DB_SERVER=db
      - DEFAULT_SECURITY_LEVEL=${DEFAULT_SECURITY_LEVEL}
      - DB_SERVER=${DB_SERVER}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - "$(pwd)/php.ini:/etc/php/7.0/apache2/php.ini"
    env_file:
      - .env

  hacker-service:
    build:
      context: .
      dockerfile: Dockerfile.machine
    container_name: attacker-container
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - "$(pwd)/txt/common.txt:/common/common.txt"
      - "$(pwd)/txt/rockyou.txt:/common/rockyou.txt"
      - "$(pwd)/txt/directory-list-2.3-medium.txt:/common/directory-list-2.3-medium.txt"


   
