FROM kalilinux/kali-rolling

RUN apt update && apt -y install zaproxy \
    gobuster \
    nikto \
    whatweb \
    wfuzz \
    sqlmap \
    xsser \
    hydra \
    metasploit-framework \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir common